# Generated by Django 5.0.2 on 2024-03-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrot_app', '0002_rename_fecha_de_incio_cursos_fecha_de_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='fecha_de_finalizacion',
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='fecha_de_inicio',
        ),
        migrations.AddField(
            model_name='cursos',
            name='aula',
            field=models.CharField(default='Aula 505', max_length=40),
        ),
    ]
