# Generated by Django 5.0.2 on 2024-04-09 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrot_app', '0006_tortas_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tortas',
            name='usuario',
        ),
    ]
